"""Base de Conhecimento - 80 Itens Completos"""
import sys, os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from database import SessionLocal
from models import KnowledgeBaseEntry, Tenant

def get_entries():
    return [
        # WINDOWS (10)
        {"problem_signature":"win_disk_full","sensor_type":"disk","severity":"critical","problem_title":"Disco C: Cheio","problem_description":"Disco >95%","symptoms":["Disco cheio"],"root_cause":"Temp files","root_cause_confidence":0.9,"solution_description":"Limpar disco","solution_steps":["cleanmgr"],"solution_commands":["cleanmgr /sagerun:1"],"auto_resolution_enabled":True,"requires_approval":False,"risk_level":"low","affected_os":["Windows Server"],"times_matched":0,"times_successful":0,"success_rate":0.92},
        {"problem_signature":"win_mem_high","sensor_type":"memory","severity":"warning","problem_title":"Memória Alta Windows","problem_description":"RAM >90%","symptoms":["Lento"],"root_cause":"Memory leak","root_cause_confidence":0.85,"solution_description":"Reiniciar processo","solution_steps":["Task Manager"],"solution_commands":["Get-Process | Sort WS"],"auto_resolution_enabled":False,"requires_approval":True,"risk_level":"medium","affected_os":["Windows Server"],"times_matched":0,"times_successful":0,"success_rate":0.78},
        {"problem_signature":"win_cpu_high","sensor_type":"cpu","severity":"warning","problem_title":"CPU Alta Windows","problem_description":"CPU >85%","symptoms":["Lento"],"root_cause":"Processo alto","root_cause_confidence":0.8,"solution_description":"Identificar processo","solution_steps":["Task Manager"],"solution_commands":["Get-Process | Sort CPU"],"auto_resolution_enabled":False,"requires_approval":True,"risk_level":"medium","affected_os":["Windows Server"],"times_matched":0,"times_successful":0,"success_rate":0.75},
        {"problem_signature":"win_iis_stopped","sensor_type":"service","severity":"critical","problem_title":"IIS Parado","problem_description":"W3SVC stopped","symptoms":["Site down"],"root_cause":"Serviço parou","root_cause_confidence":0.95,"solution_description":"Reiniciar IIS","solution_steps":["net start"],"solution_commands":["net start W3SVC"],"auto_resolution_enabled":True,"requires_approval":False,"risk_level":"low","affected_os":["Windows Server"],"times_matched":0,"times_successful":0,"success_rate":0.96},
        {"problem_signature":"win_sql_stopped","sensor_type":"service","severity":"critical","problem_title":"SQL Server Parado","problem_description":"MSSQLSERVER stopped","symptoms":["DB down"],"root_cause":"Serviço parou","root_cause_confidence":0.9,"solution_description":"Reiniciar SQL","solution_steps":["net start"],"solution_commands":["net start MSSQLSERVER"],"auto_resolution_enabled":True,"requires_approval":True,"risk_level":"medium","affected_os":["Windows Server"],"times_matched":0,"times_successful":0,"success_rate":0.88},
        {"problem_signature":"win_dns_stopped","sensor_type":"service","severity":"critical","problem_title":"DNS Server Parado","problem_description":"DNS stopped","symptoms":["Resolução falha"],"root_cause":"Serviço parou","root_cause_confidence":0.93,"solution_description":"Reiniciar DNS","solution_steps":["net start"],"solution_commands":["net start DNS"],"auto_resolution_enabled":True,"requires_approval":False,"risk_level":"low","affected_os":["Windows Server"],"times_matched":0,"times_successful":0,"success_rate":0.94},
        {"problem_signature":"win_dhcp_stopped","sensor_type":"service","severity":"critical","problem_title":"DHCP Server Parado","problem_description":"DHCP stopped","symptoms":["IPs não distribuem"],"root_cause":"Serviço parou","root_cause_confidence":0.92,"solution_description":"Reiniciar DHCP","solution_steps":["net start"],"solution_commands":["net start DHCPServer"],"auto_resolution_enabled":True,"requires_approval":False,"risk_level":"low","affected_os":["Windows Server"],"times_matched":0,"times_successful":0,"success_rate":0.93},
        {"problem_signature":"win_ad_stopped","sensor_type":"service","severity":"critical","problem_title":"Active Directory Parado","problem_description":"NTDS stopped","symptoms":["Autenticação falha"],"root_cause":"Serviço parou","root_cause_confidence":0.88,"solution_description":"Reiniciar AD","solution_steps":["net start"],"solution_commands":["net start NTDS"],"auto_resolution_enabled":False,"requires_approval":True,"risk_level":"high","affected_os":["Windows Server"],"times_matched":0,"times_successful":0,"success_rate":0.85},
        {"problem_signature":"win_spooler_stopped","sensor_type":"service","severity":"warning","problem_title":"Print Spooler Parado","problem_description":"Spooler stopped","symptoms":["Impressão falha"],"root_cause":"Fila travada","root_cause_confidence":0.92,"solution_description":"Limpar fila","solution_steps":["Limpar spool"],"solution_commands":["net stop spooler","del C:\\Windows\\System32\\spool\\PRINTERS\\*","net start spooler"],"auto_resolution_enabled":True,"requires_approval":False,"risk_level":"low","affected_os":["Windows Server"],"times_matched":0,"times_successful":0,"success_rate":0.93},
        {"problem_signature":"win_updates_pending","sensor_type":"system","severity":"warning","problem_title":"Windows Updates Pendentes","problem_description":"Updates aguardando","symptoms":["Reinício necessário"],"root_cause":"Patches instalados","root_cause_confidence":0.95,"solution_description":"Agendar reinício","solution_steps":["Verificar updates"],"solution_commands":["Get-WindowsUpdate"],"auto_resolution_enabled":False,"requires_approval":True,"risk_level":"medium","affected_os":["Windows Server"],"times_matched":0,"times_successful":0,"success_rate":0.9},
